<pre class='metadata'>
Title: Federated Learning of Cohorts
Status: CG-DRAFT
ED: https://github.com/WICG/floc
Shortname: floc
Level: 1
URL: https://wicg.github.io/floc/
Editor: Yao Xiao, Google, yaoxia@chromium.org
Editor: Josh Karlin, Google, jkarlin@chromium.org
Abstract: This incubation is not longer being pursued. See <a href="https://github.com/patcg-individual-drafts/topics">Topics API</a> instead.
Group: wicg
Repository: WICG/floc
</pre>

